export { API_BASE } from "./config";
export { ApiError, apiRequest } from "./client";
export {
  workoutSchema,
  workoutsSchema,
  createWorkoutRequestSchema,
  workoutProgramRequestSchema,
  workoutSettingsSchema,
  REST_SEC_OPTIONS,
  WORKOUT_TYPE_OPTIONS,
  FREQUENCY_OPTIONS,
  exerciseSchema,
  exercisesSchema,
  createExerciseRequestSchema,
  apiErrorSchema,
  authUserSchema,
  authSessionSchema,
  accessTokenSchema,
  meResponseSchema,
  loginRequestSchema,
  registerRequestSchema,
  type Workout,
  type WorkoutSettings,
  type CreateWorkoutInput,
  type WorkoutProgramInput,
  type Exercise,
  type CreateExerciseInput,
  type ApiErrorBody,
  type AuthUser,
  type LoginInput,
  type RegisterInput,
  loggedSetSchema,
  workoutSessionSchema,
  workoutSessionWithSetsSchema,
  workoutSessionSummarySchema,
  workoutSessionsSchema,
  workoutSessionSummariesSchema,
  logSetRequestSchema,
  patchSessionRequestSchema,
  patchLoggedSetRequestSchema,
  SESSION_STATUSES,
  type LoggedSet,
  type WorkoutSession,
  type WorkoutSessionWithSets,
  type WorkoutSessionSummary,
  type LogSetInput,
  type PatchSessionInput,
  type PatchLoggedSetInput,
  sessionHistoryResponseSchema,
  type SessionHistoryResponse,
  statsPeriodSchema,
  dailyStatPointSchema,
  recentSessionSummarySchema,
  userStatsSchema,
  type StatsPeriod,
  type DailyStatPoint,
  type RecentSessionSummary,
  type UserStats,
  workoutScheduleSchema,
  type WorkoutSchedule,
  type WorkoutDay,
  type Weekday,
} from "./schemas";
export {
  getWorkouts,
  getWorkout,
  createWorkout,
  updateWorkout,
  saveWorkoutProgram,
} from "./workouts";
export {
  getExercisesByWorkout,
  getExercise,
  createExercise,
  updateExercise,
  deleteExercise,
} from "./exercises";
export { login, register, refreshAccessToken, getMe, updateProfile, changePassword, logout } from "./auth";
export {
  startSession,
  getSessionsByWorkout,
  getSessions,
  getSession,
  getSessionHistory,
  patchSession,
  completeSession,
  abandonSession,
  logSet,
  patchLoggedSet,
  deleteLoggedSet,
} from "./sessions";
export { getStats } from "./stats";
export {
  getWorkoutDays,
  getWorkoutDay,
  createWorkoutDay,
  updateWorkoutDay,
  deleteWorkoutDay,
  setWorkoutDayWeekdays,
  getWorkoutDayExercises,
  createWorkoutDayExercise,
  getWorkoutScheduleToday,
  setScheduleOverride,
  deleteScheduleOverride,
} from "./workoutdays";
